# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cnc_pb2 as cnc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cnc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CncServiceStub(object):
    """CncService Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNetworkState = channel.unary_unary(
                '/cnc.rpc.CncService/GetNetworkState',
                request_serializer=cnc__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cnc__pb2.Topology.FromString,
                _registered_method=True)
        self.GetAllPtpData = channel.unary_unary(
                '/cnc.rpc.CncService/GetAllPtpData',
                request_serializer=cnc__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cnc__pb2.AllPtpDataResponse.FromString,
                _registered_method=True)
        self.GetAllLldpData = channel.unary_unary(
                '/cnc.rpc.CncService/GetAllLldpData',
                request_serializer=cnc__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cnc__pb2.AllLldpDataResponse.FromString,
                _registered_method=True)
        self.GetNodePtpData = channel.unary_unary(
                '/cnc.rpc.CncService/GetNodePtpData',
                request_serializer=cnc__pb2.NodeRequest.SerializeToString,
                response_deserializer=cnc__pb2.PtpNode.FromString,
                _registered_method=True)
        self.GetNodeLldpData = channel.unary_unary(
                '/cnc.rpc.CncService/GetNodeLldpData',
                request_serializer=cnc__pb2.NodeRequest.SerializeToString,
                response_deserializer=cnc__pb2.LldpNode.FromString,
                _registered_method=True)
        self.GetInterfacePtpData = channel.unary_unary(
                '/cnc.rpc.CncService/GetInterfacePtpData',
                request_serializer=cnc__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=cnc__pb2.PtpPort.FromString,
                _registered_method=True)
        self.GetInterfaceLldpData = channel.unary_unary(
                '/cnc.rpc.CncService/GetInterfaceLldpData',
                request_serializer=cnc__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=cnc__pb2.LldpPort.FromString,
                _registered_method=True)
        self.GetInterfaceGcl = channel.unary_unary(
                '/cnc.rpc.CncService/GetInterfaceGcl',
                request_serializer=cnc__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=cnc__pb2.GclConfig.FromString,
                _registered_method=True)
        self.GetInterfaceAdminGcl = channel.unary_unary(
                '/cnc.rpc.CncService/GetInterfaceAdminGcl',
                request_serializer=cnc__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=cnc__pb2.AdminGclResponse.FromString,
                _registered_method=True)
        self.GetInterfaceOperGcl = channel.unary_unary(
                '/cnc.rpc.CncService/GetInterfaceOperGcl',
                request_serializer=cnc__pb2.InterfaceRequest.SerializeToString,
                response_deserializer=cnc__pb2.OperGclResponse.FromString,
                _registered_method=True)
        self.SetNodeSchedule = channel.unary_unary(
                '/cnc.rpc.CncService/SetNodeSchedule',
                request_serializer=cnc__pb2.SetNodeScheduleRequest.SerializeToString,
                response_deserializer=cnc__pb2.SetNodeScheduleResponse.FromString,
                _registered_method=True)
        self.SetInterfaceSchedule = channel.unary_unary(
                '/cnc.rpc.CncService/SetInterfaceSchedule',
                request_serializer=cnc__pb2.SetInterfaceScheduleRequest.SerializeToString,
                response_deserializer=cnc__pb2.IetfInterface.FromString,
                _registered_method=True)


class CncServiceServicer(object):
    """CncService Definition
    """

    def GetNetworkState(self, request, context):
        """1. Return everything
        Returns the complete Topology with all Nodes, Interfaces, PTP and LLDP data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPtpData(self, request, context):
        """2. Global feature data (PTP / LLDP)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllLldpData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodePtpData(self, request, context):
        """3. node-specific data (PTP / LLDP)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeLldpData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfacePtpData(self, request, context):
        """4. interface-specific data (PTP / LLDP)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaceLldpData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaceGcl(self, request, context):
        """5. gcl/schedule data 
        Complete GCL-Config (Admin and Oper)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaceAdminGcl(self, request, context):
        """Only plannend config (Admin)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterfaceOperGcl(self, request, context):
        """Only current config (Oper)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNodeSchedule(self, request, context):
        """6. deploy new schedule to interfaces
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetInterfaceSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CncServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNetworkState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworkState,
                    request_deserializer=cnc__pb2.EmptyRequest.FromString,
                    response_serializer=cnc__pb2.Topology.SerializeToString,
            ),
            'GetAllPtpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPtpData,
                    request_deserializer=cnc__pb2.EmptyRequest.FromString,
                    response_serializer=cnc__pb2.AllPtpDataResponse.SerializeToString,
            ),
            'GetAllLldpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLldpData,
                    request_deserializer=cnc__pb2.EmptyRequest.FromString,
                    response_serializer=cnc__pb2.AllLldpDataResponse.SerializeToString,
            ),
            'GetNodePtpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodePtpData,
                    request_deserializer=cnc__pb2.NodeRequest.FromString,
                    response_serializer=cnc__pb2.PtpNode.SerializeToString,
            ),
            'GetNodeLldpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeLldpData,
                    request_deserializer=cnc__pb2.NodeRequest.FromString,
                    response_serializer=cnc__pb2.LldpNode.SerializeToString,
            ),
            'GetInterfacePtpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfacePtpData,
                    request_deserializer=cnc__pb2.InterfaceRequest.FromString,
                    response_serializer=cnc__pb2.PtpPort.SerializeToString,
            ),
            'GetInterfaceLldpData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaceLldpData,
                    request_deserializer=cnc__pb2.InterfaceRequest.FromString,
                    response_serializer=cnc__pb2.LldpPort.SerializeToString,
            ),
            'GetInterfaceGcl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaceGcl,
                    request_deserializer=cnc__pb2.InterfaceRequest.FromString,
                    response_serializer=cnc__pb2.GclConfig.SerializeToString,
            ),
            'GetInterfaceAdminGcl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaceAdminGcl,
                    request_deserializer=cnc__pb2.InterfaceRequest.FromString,
                    response_serializer=cnc__pb2.AdminGclResponse.SerializeToString,
            ),
            'GetInterfaceOperGcl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterfaceOperGcl,
                    request_deserializer=cnc__pb2.InterfaceRequest.FromString,
                    response_serializer=cnc__pb2.OperGclResponse.SerializeToString,
            ),
            'SetNodeSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNodeSchedule,
                    request_deserializer=cnc__pb2.SetNodeScheduleRequest.FromString,
                    response_serializer=cnc__pb2.SetNodeScheduleResponse.SerializeToString,
            ),
            'SetInterfaceSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.SetInterfaceSchedule,
                    request_deserializer=cnc__pb2.SetInterfaceScheduleRequest.FromString,
                    response_serializer=cnc__pb2.IetfInterface.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cnc.rpc.CncService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cnc.rpc.CncService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CncService(object):
    """CncService Definition
    """

    @staticmethod
    def GetNetworkState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetNetworkState',
            cnc__pb2.EmptyRequest.SerializeToString,
            cnc__pb2.Topology.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllPtpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetAllPtpData',
            cnc__pb2.EmptyRequest.SerializeToString,
            cnc__pb2.AllPtpDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllLldpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetAllLldpData',
            cnc__pb2.EmptyRequest.SerializeToString,
            cnc__pb2.AllLldpDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodePtpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetNodePtpData',
            cnc__pb2.NodeRequest.SerializeToString,
            cnc__pb2.PtpNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeLldpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetNodeLldpData',
            cnc__pb2.NodeRequest.SerializeToString,
            cnc__pb2.LldpNode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfacePtpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetInterfacePtpData',
            cnc__pb2.InterfaceRequest.SerializeToString,
            cnc__pb2.PtpPort.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaceLldpData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetInterfaceLldpData',
            cnc__pb2.InterfaceRequest.SerializeToString,
            cnc__pb2.LldpPort.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaceGcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetInterfaceGcl',
            cnc__pb2.InterfaceRequest.SerializeToString,
            cnc__pb2.GclConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaceAdminGcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetInterfaceAdminGcl',
            cnc__pb2.InterfaceRequest.SerializeToString,
            cnc__pb2.AdminGclResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterfaceOperGcl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/GetInterfaceOperGcl',
            cnc__pb2.InterfaceRequest.SerializeToString,
            cnc__pb2.OperGclResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNodeSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/SetNodeSchedule',
            cnc__pb2.SetNodeScheduleRequest.SerializeToString,
            cnc__pb2.SetNodeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetInterfaceSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cnc.rpc.CncService/SetInterfaceSchedule',
            cnc__pb2.SetInterfaceScheduleRequest.SerializeToString,
            cnc__pb2.IetfInterface.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
