// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "cnc.proto" (package "cnc.rpc", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CncService } from "./cnc";
import type { TopologyGraph } from "./cnc";
import type { IetfInterface } from "./cnc";
import type { SetInterfaceScheduleRequest } from "./cnc";
import type { SetNodeScheduleResponse } from "./cnc";
import type { SetNodeScheduleRequest } from "./cnc";
import type { OperGclResponse } from "./cnc";
import type { AdminGclResponse } from "./cnc";
import type { GclConfig } from "./cnc";
import type { LldpPort } from "./cnc";
import type { PtpPort } from "./cnc";
import type { InterfaceRequest } from "./cnc";
import type { LldpNode } from "./cnc";
import type { PtpNode } from "./cnc";
import type { NodeRequest } from "./cnc";
import type { AllLldpDataResponse } from "./cnc";
import type { AllPtpDataResponse } from "./cnc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Topology } from "./cnc";
import type { EmptyRequest } from "./cnc";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * CncService Definition
 *
 * @generated from protobuf service cnc.rpc.CncService
 */
export interface ICncServiceClient {
    /**
     * 1. Return everything
     * Returns the complete Topology with all Nodes, Interfaces, PTP and LLDP data.
     *
     * @generated from protobuf rpc: GetNetworkState
     */
    getNetworkState(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, Topology>;
    /**
     * 2. Global feature data (PTP / LLDP)
     *
     * @generated from protobuf rpc: GetAllPtpData
     */
    getAllPtpData(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, AllPtpDataResponse>;
    /**
     * @generated from protobuf rpc: GetAllLldpData
     */
    getAllLldpData(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, AllLldpDataResponse>;
    /**
     * 3. node-specific data (PTP / LLDP)
     *
     * @generated from protobuf rpc: GetNodePtpData
     */
    getNodePtpData(input: NodeRequest, options?: RpcOptions): UnaryCall<NodeRequest, PtpNode>;
    /**
     * @generated from protobuf rpc: GetNodeLldpData
     */
    getNodeLldpData(input: NodeRequest, options?: RpcOptions): UnaryCall<NodeRequest, LldpNode>;
    /**
     * 4. interface-specific data (PTP / LLDP)
     *
     * @generated from protobuf rpc: GetInterfacePtpData
     */
    getInterfacePtpData(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, PtpPort>;
    /**
     * @generated from protobuf rpc: GetInterfaceLldpData
     */
    getInterfaceLldpData(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, LldpPort>;
    /**
     * 5. gcl/schedule data
     * Complete GCL-Config (Admin and Oper)
     *
     * @generated from protobuf rpc: GetInterfaceGcl
     */
    getInterfaceGcl(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, GclConfig>;
    /**
     * Only plannend config (Admin)
     *
     * @generated from protobuf rpc: GetInterfaceAdminGcl
     */
    getInterfaceAdminGcl(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, AdminGclResponse>;
    /**
     * Only current config (Oper)
     *
     * @generated from protobuf rpc: GetInterfaceOperGcl
     */
    getInterfaceOperGcl(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, OperGclResponse>;
    /**
     * 6. deploy new schedule to interfaces
     *
     * @generated from protobuf rpc: SetNodeSchedule
     */
    setNodeSchedule(input: SetNodeScheduleRequest, options?: RpcOptions): UnaryCall<SetNodeScheduleRequest, SetNodeScheduleResponse>;
    /**
     * @generated from protobuf rpc: SetInterfaceSchedule
     */
    setInterfaceSchedule(input: SetInterfaceScheduleRequest, options?: RpcOptions): UnaryCall<SetInterfaceScheduleRequest, IetfInterface>;
    /**
     * @generated from protobuf rpc: GetTopologyGraph
     */
    getTopologyGraph(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, TopologyGraph>;
}
/**
 * CncService Definition
 *
 * @generated from protobuf service cnc.rpc.CncService
 */
export class CncServiceClient implements ICncServiceClient, ServiceInfo {
    typeName = CncService.typeName;
    methods = CncService.methods;
    options = CncService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 1. Return everything
     * Returns the complete Topology with all Nodes, Interfaces, PTP and LLDP data.
     *
     * @generated from protobuf rpc: GetNetworkState
     */
    getNetworkState(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, Topology> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, Topology>("unary", this._transport, method, opt, input);
    }
    /**
     * 2. Global feature data (PTP / LLDP)
     *
     * @generated from protobuf rpc: GetAllPtpData
     */
    getAllPtpData(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, AllPtpDataResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, AllPtpDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllLldpData
     */
    getAllLldpData(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, AllLldpDataResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, AllLldpDataResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 3. node-specific data (PTP / LLDP)
     *
     * @generated from protobuf rpc: GetNodePtpData
     */
    getNodePtpData(input: NodeRequest, options?: RpcOptions): UnaryCall<NodeRequest, PtpNode> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<NodeRequest, PtpNode>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetNodeLldpData
     */
    getNodeLldpData(input: NodeRequest, options?: RpcOptions): UnaryCall<NodeRequest, LldpNode> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<NodeRequest, LldpNode>("unary", this._transport, method, opt, input);
    }
    /**
     * 4. interface-specific data (PTP / LLDP)
     *
     * @generated from protobuf rpc: GetInterfacePtpData
     */
    getInterfacePtpData(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, PtpPort> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<InterfaceRequest, PtpPort>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetInterfaceLldpData
     */
    getInterfaceLldpData(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, LldpPort> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<InterfaceRequest, LldpPort>("unary", this._transport, method, opt, input);
    }
    /**
     * 5. gcl/schedule data
     * Complete GCL-Config (Admin and Oper)
     *
     * @generated from protobuf rpc: GetInterfaceGcl
     */
    getInterfaceGcl(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, GclConfig> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<InterfaceRequest, GclConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * Only plannend config (Admin)
     *
     * @generated from protobuf rpc: GetInterfaceAdminGcl
     */
    getInterfaceAdminGcl(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, AdminGclResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<InterfaceRequest, AdminGclResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Only current config (Oper)
     *
     * @generated from protobuf rpc: GetInterfaceOperGcl
     */
    getInterfaceOperGcl(input: InterfaceRequest, options?: RpcOptions): UnaryCall<InterfaceRequest, OperGclResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<InterfaceRequest, OperGclResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 6. deploy new schedule to interfaces
     *
     * @generated from protobuf rpc: SetNodeSchedule
     */
    setNodeSchedule(input: SetNodeScheduleRequest, options?: RpcOptions): UnaryCall<SetNodeScheduleRequest, SetNodeScheduleResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetNodeScheduleRequest, SetNodeScheduleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetInterfaceSchedule
     */
    setInterfaceSchedule(input: SetInterfaceScheduleRequest, options?: RpcOptions): UnaryCall<SetInterfaceScheduleRequest, IetfInterface> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetInterfaceScheduleRequest, IetfInterface>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTopologyGraph
     */
    getTopologyGraph(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, TopologyGraph> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, TopologyGraph>("unary", this._transport, method, opt, input);
    }
}
