@startuml
skinparam style strictuml
skinparam MaxMessageSize 150

autonumber

participant "JsonImporter" as JI
participant "NetworkManager" as NM
participant "GclXmlBuilder" as GXB
participant "NetconfSession" as NS
box "Remote TSN Node" #f9f9f9
    participant "tsnctrld" as TCD
    participant "NetconfNetlinkMapper" as MAP
    participant "QdiscManager" as QM
    participant "NetlinkSocket" as NLS
end box

group Initialization & Loading
JI -> NM : importFromFile("topology.json")
JI -> NM : importInventory("nodes.json")
activate NM
NM -> NS : connect(ip, port, user, pass)
deactivate NM
end

group Configuration Deployment Flow
[-> NM : deployConfigToAll()
activate NM

NM -> GXB : buildXmlForNode(node)
activate GXB
GXB --> NM : return <xml>GCL_Config</xml>
deactivate GXB

NM -> NS : editData(configXml)
NS -> TCD : [NETCONF Edit-Config RPC]
activate TCD
end

group Daemon Processing (Netlink Mapping)

TCD -> TCD : changeInterfaceCallback()
note right: Triggered by Sysrepo subscription

TCD -> MAP : mapToTaprio(ietfInterface)
activate MAP
MAP --> TCD : return TaprioConfig
deactivate MAP

TCD -> QM : setQdisc(NetlinkSocket, ifname, taprioConfig)
activate QM

QM -> NLS : sendMessage(nlh, len)
activate NLS
NLS -> Kernel : Send RTM_NEWQDISC (taprio)
Kernel --> NLS : Netlink ACK
NLS --> QM : return response
deactivate NLS

QM --> TCD : Success
deactivate QM

TCD --> NS : <ok/> RPC Reply
deactivate TCD

NS --> NM : return true
deactivate NM
end

group LLDP Discovery (Feedback Loop)
NM -> NS : getData("/ietf-lldp:lldp")
NS -> TCD : [NETCONF Get-Data RPC]
TCD -> NS : return LLDP Oper Data
NM -> NM : fetchLldpData()
end

@enduml