# The university of Stuttgart blocks regular NTP servers with its firewall, we need to use the NTP servers they provide
server time1.uni-stuttgart.de iburst
server time2.uni-stuttgart.de iburst
server time3.uni-stuttgart.de iburst

# Look for other config files with NTP servers:
sourcedir /run/chrony-dhcp
sourcedir /etc/chrony/sources.d

# File containing ID/key pairs for NTP authentication
keyfile /etc/chrony/chrony.keys

# Rate information will be stored in this file
driftfile /var/lib/chrony/chrony.drift

# Where to store NTS keys and cookies
ntsdumpdir /var/lib/chrony

# Uncomment the following line to turn logging on.
#log tracking measurements statistics

# Log files location
logdir /var/log/chrony

# Stop bad estimates upsetting machine clock
maxupdateskew 100.0

# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can't be used along with the 'rtcfile' directive.
rtcsync

# Step the system clock instead of slewing it if the adjustment is larger than
# one second, but only in the first three clock updates.
makestep 1.0 3

# Get TAI-UTC offset and leap seconds from the system tz database.
# This directive must be commented out when using time sources serving
# leap-smeared time.
leapseclist /usr/share/zoneinfo/leap-seconds.list

# Slew the clock with 694ppm, correcting about 1 minute in a 24 hour period
maxslewrate 694

# When a leap second occurs, slew the clock instead of skipping/repeating a second
leapsecmode slew
